config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: "sessions#create"

  get '/search', to: "search#new", as: :new_search
  post '/search', to: "search#create", as: :create_search
  post '/ev_search', to: "ev_search#create", as: :create_ev_search

  get '/map', to: "map#show"
  get '/ev_map', to: "ev_map#show"

  get '/about', to: "about#index", as: :about

  get '/leaderboard', to: "leaderboard#index"
  get '/logout', to: 'sessions#destroy', as: "logout"

  namespace :admin do
    get 'dashboard', as: 'dashboard', to: 'users#index'
    resources :users, only: [:index, :update]
  end

  namespace :dashboard do
    get '/', to: "users#show"
    resources :trip_logs, only: [:new, :create, :index]
  end
  resources :charge_spots, only: [:new]
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :require_user

  def new
  end

  def create
    coordinates = GeocoderFacade.get_lat_lon(cookies["coordinates"] || params["search_location"])
    cookies.delete "coordinates";
    return handle_invalid_location(coordinates) unless coordinates
    session[:search] = {
      range: params[:ev_range],
      activity: get_activities_search(params["activities"]),
      lat: coordinates[:lat],
      lon: coordinates[:lon]
    }

    redirect_to map_path
  end

  private

  def get_activities_search(activities_params)
    activities_params.map { |p| eval(p).values}.flatten
  end

  def handle_invalid_location(coordinates)
    if coordinates == nil
      flash[:error] = 'Zip Code must be entered or press \'Use Current Location\''
    elsif coordinates == false
      flash[:error] = 'Invalid Zip Code - try again or press \'Use Current Location\''
    end
    redirect_to new_search_path
  end
end

app/views/search/new.html.erb
<div class="form">
  <%= form_tag create_search_path, id: "search-form" do %>
    <p><%= label_tag :ev_range, "Your EV Range (in miles):" , class: "form-text"%></p>
    <p><%= select_tag :ev_range, options_for_select(ranges), class: "form-control" %></p>
    <p id="restaurants"><%= label_tag :activities, "Restaurants:" , class: "form-text checks" %>
    <%= check_box_tag("activities[]", value: "restaurants") %></p>
    <p id="museums"><%= label_tag :activities, "Museums:" , class: "form-text checks"%>
    <%= check_box_tag("activities[]", value: "museums") %></p>
    <p id="parks"><%= label_tag :activities, "Parks:" , class: "form-text checks"%>
    <%= check_box_tag("activities[]", value: "parks") %></p>
    <p><%= label_tag :search_location, "Enter Zip Code:" , class: "form-text"%></p>
    <p><%= text_field_tag :search_location, nil, id: "search-location", class: "form-control" %></p>
    <p><%= button_tag "Use Current Location", type: "button", id: "current-location", class: "btn btn-primary" %></p>
    <p><%= submit_tag "Search", id: "submit-search", class: "btn btn-primary" %></p>
  <% end %>
</div>
<%= javascript_include_tag 'event_listeners' %>