config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: "sessions#create"

  get '/search', to: "search#new", as: :new_search
  post '/search', to: "search#create", as: :create_search
  post '/ev_search', to: "ev_search#create", as: :create_ev_search

  get '/map', to: "map#show"
  get '/ev_map', to: "ev_map#show"

  get '/about', to: "about#index", as: :about

  get '/leaderboard', to: "leaderboard#index"
  get '/logout', to: 'sessions#destroy', as: "logout"

  namespace :admin do
    get 'dashboard', as: 'dashboard', to: 'users#index'
    resources :users, only: [:index, :update]
  end

  namespace :dashboard do
    get '/', to: "users#show"
    resources :trip_logs, only: [:new, :create, :index]
  end
  resources :charge_spots, only: [:new]
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/welcome/index.html.erb
<body>
  <!-- Page Content -->
  <section>
    <div class="main-container">
      <p id="tagline">Adventure is within reach</p>
      <% unless current_user %>
        <%= button_to "Sign in With Google", google_login_path, method: :get, class: "btn btn-primary", id: "root-btn"  %>
      <% end %>
      <% if current_user %>
        <%= button_to "Search for Locations", new_search_path, method: :get, class: "btn btn-primary", id: "root-btn" %>
      <% end %>
    </div>
  </section>
</body>