config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: "sessions#create"

  get '/search', to: "search#new", as: :new_search
  post '/search', to: "search#create", as: :create_search
  post '/ev_search', to: "ev_search#create", as: :create_ev_search

  get '/map', to: "map#show"
  get '/ev_map', to: "ev_map#show"

  get '/about', to: "about#index", as: :about

  get '/leaderboard', to: "leaderboard#index"
  get '/logout', to: 'sessions#destroy', as: "logout"

  namespace :admin do
    get 'dashboard', as: 'dashboard', to: 'users#index'
    resources :users, only: [:index, :update]
  end

  namespace :dashboard do
    get '/', to: "users#show"
    resources :trip_logs, only: [:new, :create, :index]
  end
  resources :charge_spots, only: [:new]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RangeSociety</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset='utf-8' />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="google-signin-client_id" content="<%= ENV['CLIENT_ID'] %>.apps.googleusercontent.com">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
    integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
    crossorigin=""/>
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css' rel='stylesheet' />
    <script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
    integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
    crossorigin=""></script>
  </head>

  <body>
    <div class="background">
      <div class="layer">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container">
            <a class="navbar-brand" id="title">Range Society</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                  <%= link_to "Home", root_path, class: "nav-link"%>
                </li>
                <li class="nav-item">
                  <%= link_to "About", about_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Carbon Leaderboard", leaderboard_path, class: "nav-link" %>
                </li>
                <% if current_user %>
                <li class="nav-item">
                  <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "My Trips", dashboard_trip_logs_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "New Search", new_search_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Logout", logout_path, class: "nav-link" %>
                </li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
        <% flash.each do |type, message| %>
          <p class="<%= type %>"><%= message %></p>
        <% end %>
        <div class="main-scroll">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>